[connections]
[connections.airflow]
account = "zd27083.us-east-2.aws"
user = "airflow_user"
database = "airflow_db"
schema = "airflow_schema"
warehouse = "airflow_wh"
role = "airflow_admin_rl"
connection_timeout = 600
